server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: food-service
  cloud:
    gateway:
      routes:
        - id: food-service
          uri: lb://food-service