server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
#        predicates:
#        - Path=/api/v1/user/**
#      - id: article-service
#        uri: lb://article-service
#        predicates:
#        - Path=/api/v1/article/**
        